import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

export default function Home (props:any) {
  const listing = trpc.useQuery(["example.get-all"]);
  console.log(listing.data)
  return (
    <>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
           <a href="#"><span className="text-purple-300 hover:text-gray-700">New Listing </span></a>or <a href="#"><span className="text-orange-300 hover:text-gray-700">Under Contract</span></a>
        </h1>
        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          {listing.data ? <p>{listing.data[0]?.seller1}</p> : <p>Loading..</p>}
        </div>
      </main>
    </>
  );
};