import Head from "next/head";
import Link from 'next/link';
import router from 'next/router';
import { trpc } from "../utils/trpc";

const ClientNameCreator: React.FC = () => {
  const client = trpc.useContext();
  const {mutate} = trpc.useMutation("form-client.create", {
    onSuccess: () => {
      client.invalidateQueries("form-client.get-all");
    },
  });

return (
  <input 
    onKeyDown={(ev)=>{
      if (ev.key === "Enter") {
        console.log("Enter pressed!", ev.currentTarget.value);
        mutate({clientNames: ev.currentTarget.value});
        ev.currentTarget.value = "";
        }
    }}
    ></input>
);
};

export default function Home () {

  const listing = trpc.useQuery(["form-client.get-all"]);
  return (
    <>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
        <Link href="/"><a className={router.pathname == "/" ? "active" : ""}><span className="text-purple-300 active:text-gray-700">New Listing </span></a></Link>or <Link href="/"><a className={router.pathname == "/" ? "active" : ""}><span className="text-orange-300 active:text-gray-700">Under Contract</span></a></Link>
        </h1>
        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          {listing.data ? 
          <div className="p-6 flex flex-col">
            <div className="flex flex-col">
            <div className="text-2xl font-bold"> Client Names<div/>
            {listing.data.map((Client) => {
              return (
              <div key={Client.id} className="my-2">
                {Client.clientNames}
                </div>
                );
            })} 
            </div>
            </div>
            <ClientNameCreator /> 
            </div> 
            : <p>Loading..</p>}
        </div>
      </main>
    </>
  );
};